### ISSUE TITLE
Error popup displayed twice

### ISSUE THREAD

**Issue by Chistaen** [MichelGlazenborg/Parking_Garage#128]
Fixed in #127 

Feedback?

**Comment by MichelGlazenborg** [comment]
Not fixed, still displayed twice when entering "a" in field for runFor

**Comment by Chistaen** [comment]
Hmm, apparently the same code was used in several other methods. Only two of them were fixed; submit() was not one of them.

**Comment by Chistaen** [comment]
#129

**Comment by MichelGlazenborg** [comment]
Fixed
