### ISSUE TITLE
Unchecked calls to ...

### ISSUE THREAD

**Issue by Chistaen** [MichelGlazenborg/Parking_Garage#150]
Just in case I forget, you can ignore this one.

**Comment by CrazyMazzo** [comment]
Deze kan gesloten worden toch ?

**Comment by Chistaen** [comment]
Nope, nog niet, dit is nog niet opgelost.

**Comment by CrazyMazzo** [comment]
Dit us zeker een deel code cleanup ?

**Comment by Chistaen** [comment]
Uhu, IntelliJ heeft een aantal lijnen in één van de models (weet zo niet welke) geel gemarkeerd. Hoewel deze geen foutmeldingen van Java opleveren, zou het mooi zijn als we kunnen achterhalen waar dit door komt. Dus idd een deel code cleanup.

**Comment by Chistaen** [comment]
Om de een of andere reden zijn er nu geen meldingen meer.. Nja, beter. :P
