### ISSUE TITLE
Simulator throwing NullPointerExceptions

### ISSUE THREAD

**Issue by Jobiir** [MichelGlazenborg/Parking_Garage#59]
The simulator throws many NullPointerExceptions, possibly because of the garage being full and the simulator attempting to place new cars outside of the garage boundaries.

**Comment by Chistaen** [comment]
Has this been fixed yet?

**Comment by Jobiir** [comment]
No, but it is verified to happen when the garage is full and new cars attempt to enter.

**Comment by Chistaen** [comment]
Okay, got it, thanks
